//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAET.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidatos()
        {
            this.ChatEntrevistaCandidato = new HashSet<ChatEntrevistaCandidato>();
            this.EntrevistaCandidato = new HashSet<EntrevistaCandidato>();
        }
    
        public int IdCandidato { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdTitulacion { get; set; }
        public Nullable<int> IdExperiencia { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string NIFNIE { get; set; }
        public string Apodo { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public byte[] Pwd { get; set; }
        public bool Activo { get; set; }
    
        public virtual CategoriaProfesional CategoriaProfesional { get; set; }
        public virtual Experiencia Experiencia { get; set; }
        public virtual Titulacion Titulacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatEntrevistaCandidato> ChatEntrevistaCandidato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrevistaCandidato> EntrevistaCandidato { get; set; }
    }
}
