//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAET.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultimediaEntrevistaCandidato
    {
        public int IdMultiEntrevistaCandidato { get; set; }
        public Nullable<int> IdEntrevistaCandidato { get; set; }
        public Nullable<int> IdValoracion { get; set; }
        public byte[] Contenido { get; set; }
        public bool Finalizacion { get; set; }
        public string UsuarioValoracion { get; set; }
        public Nullable<System.DateTime> FechaValoracion { get; set; }
        public Nullable<int> IdMultimedia { get; set; }
    
        public virtual EntrevistaCandidato EntrevistaCandidato { get; set; }
        public virtual Valoracion Valoracion { get; set; }
        public virtual Multimedia Multimedia { get; set; }
    }
}
