//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAET.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuestas()
        {
            this.EntrevistaPreguntaTest = new HashSet<EntrevistaPreguntaTest>();
        }
    
        public int IdRespuesta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public Nullable<int> IdValoracion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Correcta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrevistaPreguntaTest> EntrevistaPreguntaTest { get; set; }
        public virtual Preguntas Preguntas { get; set; }
        public virtual Valoracion Valoracion { get; set; }
    }
}
