//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAET.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwEntrevistaCandidatos
    {
        public int IdCandidato { get; set; }
        public int IdEntrevistaCandidato { get; set; }
        public Nullable<int> IdEntrevista { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<decimal> ValoracionFinal { get; set; }
    }
}
