//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAET.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preguntas()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }
    
        public int IdPregunta { get; set; }
        public Nullable<int> IdTecnologia { get; set; }
        public Nullable<int> IdDificultad { get; set; }
        public Nullable<int> IdValoracion { get; set; }
        public Nullable<int> IdTipoPregunta { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Dificultad Dificultad { get; set; }
        public virtual Tecnologia Tecnologia { get; set; }
        public virtual TipoPregunta TipoPregunta { get; set; }
        public virtual Valoracion Valoracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
